eureka: 
  client:
    serviceUrl:
      defaultZone: http://120.25.224.153:1111/eureka/
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://118.89.146.110:3306/insurancestore
    username: mysql
    password: Mm_1989321
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 5  
    minIdle: 5  
    maxActive: 20  
    maxWait: 60000  
    timeBetweenEvictionRunsMillis: 60000  
    minEvictableIdleTimeMillis: 300000  
    validationQuery: SELECT 1 FROM DUAL  
    testWhileIdle: true  
    testOnBorrow: false  
    testOnReturn: false  
    poolPreparedStatements: true  
    maxPoolPreparedStatementPerConnectionSize: 20  
    filters: stat,wall,log4j  
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000  
  redis:
    database: 1
    password: Mm_1989321
    pool:
      max-active: 18
      max-wait: 4
      max-idle: 16
      min-idle: 2     
    sentinel: 
      master: mymaster
      nodes: 118.89.146.110:26379,120.25.224.153:26379
org: 
  quartz:
    scheduler:
      instanceName: myscheduler
      instanceId: AUTO
    threadPool: 
      class: org.quartz.simpl.SimpleThreadPool
      threadCount: 5
      threadPriority: 5
    jobStore: 
      misfireThreshold: 60000
      class: org.quartz.impl.jdbcjobstore.JobStoreTX
      tablePrefix: QRTZ_
      dataSource: myDS
      isClustered: false
      clusterCheckinInterval: 2000
    dataSource: 
      myDS: 
        driver: com.mysql.cj.jdbc.Driver
        URL: jdbc:mysql://118.89.146.110:3306/insurancestore
        user: mysql
        password: Mm_1989321
        maxConnections: 10
 
      
